// Generated by gencpp from file spark_carry_object/status.msg
// DO NOT EDIT!


#ifndef SPARK_CARRY_OBJECT_MESSAGE_STATUS_H
#define SPARK_CARRY_OBJECT_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spark_carry_object
{
template <class ContainerAllocator>
struct status_
{
  typedef status_<ContainerAllocator> Type;

  status_()
    : status(0)  {
    }
  status_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::spark_carry_object::status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spark_carry_object::status_<ContainerAllocator> const> ConstPtr;

}; // struct status_

typedef ::spark_carry_object::status_<std::allocator<void> > status;

typedef boost::shared_ptr< ::spark_carry_object::status > statusPtr;
typedef boost::shared_ptr< ::spark_carry_object::status const> statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spark_carry_object::status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spark_carry_object::status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spark_carry_object::status_<ContainerAllocator1> & lhs, const ::spark_carry_object::status_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spark_carry_object::status_<ContainerAllocator1> & lhs, const ::spark_carry_object::status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spark_carry_object

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spark_carry_object::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spark_carry_object::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spark_carry_object::status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spark_carry_object::status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spark_carry_object::status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spark_carry_object::status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spark_carry_object::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "284aa12dd9e9e760802ac9f38036ea5e";
  }

  static const char* value(const ::spark_carry_object::status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x284aa12dd9e9e760ULL;
  static const uint64_t static_value2 = 0x802ac9f38036ea5eULL;
};

template<class ContainerAllocator>
struct DataType< ::spark_carry_object::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spark_carry_object/status";
  }

  static const char* value(const ::spark_carry_object::status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spark_carry_object::status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 status\n"
;
  }

  static const char* value(const ::spark_carry_object::status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spark_carry_object::status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spark_carry_object::status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spark_carry_object::status_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPARK_CARRY_OBJECT_MESSAGE_STATUS_H
