// Generated by gencpp from file spark_fetchtea/scene.msg
// DO NOT EDIT!


#ifndef SPARK_FETCHTEA_MESSAGE_SCENE_H
#define SPARK_FETCHTEA_MESSAGE_SCENE_H

#include <ros/service_traits.h>


#include <spark_fetchtea/sceneRequest.h>
#include <spark_fetchtea/sceneResponse.h>


namespace spark_fetchtea
{

struct scene
{

typedef sceneRequest Request;
typedef sceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct scene
} // namespace spark_fetchtea


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::spark_fetchtea::scene > {
  static const char* value()
  {
    return "db8f4e4997dce45d9d28ca5947e2928a";
  }

  static const char* value(const ::spark_fetchtea::scene&) { return value(); }
};

template<>
struct DataType< ::spark_fetchtea::scene > {
  static const char* value()
  {
    return "spark_fetchtea/scene";
  }

  static const char* value(const ::spark_fetchtea::scene&) { return value(); }
};


// service_traits::MD5Sum< ::spark_fetchtea::sceneRequest> should match
// service_traits::MD5Sum< ::spark_fetchtea::scene >
template<>
struct MD5Sum< ::spark_fetchtea::sceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::spark_fetchtea::scene >::value();
  }
  static const char* value(const ::spark_fetchtea::sceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::spark_fetchtea::sceneRequest> should match
// service_traits::DataType< ::spark_fetchtea::scene >
template<>
struct DataType< ::spark_fetchtea::sceneRequest>
{
  static const char* value()
  {
    return DataType< ::spark_fetchtea::scene >::value();
  }
  static const char* value(const ::spark_fetchtea::sceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::spark_fetchtea::sceneResponse> should match
// service_traits::MD5Sum< ::spark_fetchtea::scene >
template<>
struct MD5Sum< ::spark_fetchtea::sceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::spark_fetchtea::scene >::value();
  }
  static const char* value(const ::spark_fetchtea::sceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::spark_fetchtea::sceneResponse> should match
// service_traits::DataType< ::spark_fetchtea::scene >
template<>
struct DataType< ::spark_fetchtea::sceneResponse>
{
  static const char* value()
  {
    return DataType< ::spark_fetchtea::scene >::value();
  }
  static const char* value(const ::spark_fetchtea::sceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SPARK_FETCHTEA_MESSAGE_SCENE_H
