// Generated by gencpp from file spark_base/SparkBaseOdom.msg
// DO NOT EDIT!


#ifndef SPARK_BASE_MESSAGE_SPARKBASEODOM_H
#define SPARK_BASE_MESSAGE_SPARKBASEODOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spark_base
{
template <class ContainerAllocator>
struct SparkBaseOdom_
{
  typedef SparkBaseOdom_<ContainerAllocator> Type;

  SparkBaseOdom_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
    }
  SparkBaseOdom_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::spark_base::SparkBaseOdom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spark_base::SparkBaseOdom_<ContainerAllocator> const> ConstPtr;

}; // struct SparkBaseOdom_

typedef ::spark_base::SparkBaseOdom_<std::allocator<void> > SparkBaseOdom;

typedef boost::shared_ptr< ::spark_base::SparkBaseOdom > SparkBaseOdomPtr;
typedef boost::shared_ptr< ::spark_base::SparkBaseOdom const> SparkBaseOdomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spark_base::SparkBaseOdom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spark_base::SparkBaseOdom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spark_base::SparkBaseOdom_<ContainerAllocator1> & lhs, const ::spark_base::SparkBaseOdom_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spark_base::SparkBaseOdom_<ContainerAllocator1> & lhs, const ::spark_base::SparkBaseOdom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spark_base

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spark_base::SparkBaseOdom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spark_base::SparkBaseOdom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spark_base::SparkBaseOdom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "47802147045815b06859cca542c21d31";
  }

  static const char* value(const ::spark_base::SparkBaseOdom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x47802147045815b0ULL;
  static const uint64_t static_value2 = 0x6859cca542c21d31ULL;
};

template<class ContainerAllocator>
struct DataType< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spark_base/SparkBaseOdom";
  }

  static const char* value(const ::spark_base::SparkBaseOdom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# return the absolute angular from sparkbase's position （x , y ）, yaw indicate yaw\n"
"float32 x\n"
"float32 y\n"
"float32 yaw\n"
;
  }

  static const char* value(const ::spark_base::SparkBaseOdom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SparkBaseOdom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spark_base::SparkBaseOdom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spark_base::SparkBaseOdom_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPARK_BASE_MESSAGE_SPARKBASEODOM_H
